MicrosoftLearning/mslearn-ai-language

- Instructions/Labs/01-analyze-text.md
- Labfiles/01-analyze-text/C-Sharp/text-analysis/appsettings.json
-updated appsettings.json to use correct variable name for key
-small change to instructions
> Lab01 Small update

- Instructions/Labs/02-qna.md
updated folder name and added "bash" to the command to run it
> Lab02 Small update

- Instructions/Labs/03b-clu-app.md
-updated folder refence
-added instruction to clone repo in VScode
-some small md formatting fixes
> Lab03b Small update

- Instructions/Labs/04-text-classification.md
- added reference to save the files to a folder of choice
- added steps to enable anonymous blog access
> Lab04 Small updates

- Instructions/Labs/05-extract-custom-entities.md
- Labfiles/05-custom-entity-recognition/extract-entities.ps1
- updated instructions
- added placeholder names for the key and endpoint values in the ps1 file
> Lab05 Small updates

- Instructions/Labs/06-translate-text.md
- Labfiles/06-translate-text/C-Sharp/text-translation/Program.cs
- Labfiles/06-translate-text/Python/text-translation/text-translation.py
- fixed some md
- updated code to match correct fodler names
- updated program files code to show correct comment names
> Lab06 Small updates

- Instructions/Labs/07-speech.md
updated instructions and links to documentation pages
> Lab07 small updates

- Instructions/Labs/08-translate-speech.md
updates to formatting and documentation links
> Lab08 Small updates

- Labfiles/02-qna/Python/qna-app/qna-app.py
Updated the config variables, this closes #17
> Solves Issue #17

- Instructions/Exercises/01-analyze-text.md
Adds step to install dotenv package for the Python version of the exercise.
Closes #13
> Install dotenv package

- Instructions/Exercises/05-extract-custom-entities.md
Typo in exercise file '05-extract-custom-entities.md'.
> Fixed typo in exercise 05

- Instructions/Exercises/05-extract-custom-entities.md
> Corrected a 'new' spelling mistake

- Instructions/Exercises/06-translate-text.md
The first line removes an opening parentheses in the string to make it consistent with the Python output.
The second line moves the if statement to a new line to make it read as clean as the other C# samples.
> Made C# code snippets consistent with Python.

- Instructions/Exercises/01-analyze-text.md
- Instructions/Exercises/03-language-understanding.md
- Instructions/Exercises/05-extract-custom-entities.md
- Instructions/Exercises/06-translate-text.md
- Instructions/Exercises/07-speech.md
- Instructions/Exercises/08-translate-speech.md
I fix a typo in lab 05.
I add instructions to click on Create button during the resource creation in lab 01,03,06,07,08. This instruction is already in the other labs.
> Add detailed instructions during resource creation in different labs. 

- Instructions/Exercises/05-extract-custom-entities.md
> Corrected several typos

- Instructions/Exercises/01-analyze-text.md
> Corrected folder name in lab 5 instructions

- Instructions/Exercises/03-language-understanding.md
> Update 03-language-understanding.md typo

- Instructions/Exercises/05-extract-custom-entities.md
fixed numbering, fixed small typo
> minor text edits

- Instructions/Exercises/04-text-classification.md
- Instructions/Exercises/05-extract-custom-entities.md
> Update 04-text-classification.md & Instructions/Exercises/05-extract-custom-entities.md

- Instructions/Labs/07-speech.md
- Instructions/Labs/09-audio-chat.md
This pull request includes minor adjustments to file paths and a code change for handling asynchronous operations in C#. The most important changes are grouped below:
* Updated directory names from `C-sharp` to `C-Sharp` in `Instructions/Labs/07-speech.md` and `Instructions/Labs/09-audio-chat.md` to maintain consistent capitalization in file paths. [[1]](diffhunk://#diff-94790280f64cf8afdd7cf627ee3c41a544c54e61c36be5ade92f7bfaf7af4bcdL65-R65) [[2]](diffhunk://#diff-a135827526268f279910be366469f6d6e9eb3810565fe4984bfbe75472590eabL91-R91)
* Replaced `await` with `.Result` in `GetByteArrayAsync` to handle the asynchronous operation synchronously in `Instructions/Labs/09-audio-chat.md`. This change may have implications for thread blocking and should be reviewed carefully.
> Small fixes I found while going through the LAB

- Instructions/Labs/03-language-understanding.md
- Instructions/Labs/04-text-classification.md
This pull request updates instructions in two lab files to streamline the process of provisioning an Azure AI Language service resource. The changes improve clarity and consistency in the step-by-step guidance.
* [`Instructions/Labs/03-language-understanding.md`](diffhunk://#diff-260e08c5c3837b919109063a520e32f65e28cd7f8aac548b37add22cc6c33b03L35-R36): Simplified the steps for creating an Azure AI Language service resource by replacing "search for Azure AI services" with "select Create a resource" and refining the search instructions for the Language service.
* [`Instructions/Labs/04-text-classification.md`](diffhunk://#diff-48aabb40f953917d5380e75b29418266f13d51cf0e980907e971028676f931e7L25-R27): Updated the instructions to align with the changes in the previous lab file, ensuring …
> LABS 03-04: Change the reference to Azure AI Services service (it is not valid anymore)
